"""Recettes supplémentaires (sans porc, sans alcool). Fusionnées dans donnees.py.
Format identique à donnees.py : ingrédients pour 2 personnes (quantité, unité, nom, prix Leclerc, prix Lidl)."""

BASE_PLUS = [
    # Entrées
    ("Houmous Maison", "Entrée", "10 min", "Facile"),
    ("Taboulé Libanais", "Entrée", "20 min", "Facile"),
    ("Salade Grecque", "Entrée", "10 min", "Facile"),
    ("Soupe de Lentilles Corail", "Entrée", "30 min", "Facile"),
    ("Falafels", "Entrée", "30 min", "Moyen"),
    ("Brick à l'Œuf", "Entrée", "20 min", "Moyen"),
    # Plats
    ("Poulet Rôti aux Herbes", "Plat", "1 h 05", "Facile"),
    ("Tajine de Poulet aux Olives", "Plat", "1 h", "Moyen"),
    ("Couscous au Poulet", "Plat", "50 min", "Moyen"),
    ("Chili con Carne", "Plat", "45 min", "Facile"),
    ("Lasagnes au Bœuf", "Plat", "1 h 10", "Moyen"),
    ("Curry de Pois Chiches", "Plat", "30 min", "Facile"),
    ("Poulet Yassa", "Plat", "45 min", "Moyen"),
    ("Kefta de Bœuf", "Plat", "25 min", "Facile"),
    ("Omelette aux Champignons", "Plat", "15 min", "Facile"),
    ("Cabillaud au Four", "Plat", "25 min", "Facile"),
    ("Gambas à l'Ail", "Plat", "15 min", "Facile"),
    ("Hachis Parmentier", "Plat", "1 h", "Moyen"),
    # Desserts
    ("Crêpes", "Dessert", "30 min", "Facile"),
    ("Riz au Lait", "Dessert", "40 min", "Facile"),
    ("Clafoutis aux Cerises", "Dessert", "50 min", "Moyen"),
    ("Crème Brûlée", "Dessert", "1 h", "Moyen"),
    ("Panna Cotta aux Fruits Rouges", "Dessert", "25 min", "Facile"),
    ("Cookies Pépites de Chocolat", "Dessert", "25 min", "Facile"),
]

EMOJIS_PLUS = {
    "Houmous Maison": "🧆", "Taboulé Libanais": "🥗", "Salade Grecque": "🫒",
    "Soupe de Lentilles Corail": "🍲", "Falafels": "🧆", "Brick à l'Œuf": "🥟",
    "Poulet Rôti aux Herbes": "🍗", "Tajine de Poulet aux Olives": "🥘", "Couscous au Poulet": "🥘",
    "Chili con Carne": "🌶️", "Lasagnes au Bœuf": "🍝", "Curry de Pois Chiches": "🍛",
    "Poulet Yassa": "🍋", "Kefta de Bœuf": "🍢", "Omelette aux Champignons": "🍳",
    "Cabillaud au Four": "🐟", "Gambas à l'Ail": "🦐", "Hachis Parmentier": "🥔",
    "Crêpes": "🥞", "Riz au Lait": "🍚", "Clafoutis aux Cerises": "🍒",
    "Crème Brûlée": "🍮", "Panna Cotta aux Fruits Rouges": "🍓", "Cookies Pépites de Chocolat": "🍪",
}

WIKI_PLUS = {
    "Houmous Maison": ("en", "Hummus"), "Taboulé Libanais": ("en", "Tabbouleh"),
    "Salade Grecque": ("en", "Greek salad"), "Soupe de Lentilles Corail": ("en", "Lentil soup"),
    "Falafels": ("en", "Falafel"), "Brick à l'Œuf": ("en", "Brik"),
    "Poulet Rôti aux Herbes": ("en", "Roast chicken"), "Tajine de Poulet aux Olives": ("en", "Tajine"),
    "Couscous au Poulet": ("en", "Couscous"), "Chili con Carne": ("en", "Chili con carne"),
    "Lasagnes au Bœuf": ("en", "Lasagne"), "Curry de Pois Chiches": ("en", "Chana masala"),
    "Poulet Yassa": ("en", "Yassa"), "Kefta de Bœuf": ("en", "Kofta"),
    "Omelette aux Champignons": ("en", "Omelette"), "Cabillaud au Four": ("en", "Atlantic cod"),
    "Gambas à l'Ail": ("en", "Scampi"), "Hachis Parmentier": ("fr", "Hachis parmentier"),
    "Crêpes": ("en", "Crêpe"), "Riz au Lait": ("en", "Rice pudding"),
    "Clafoutis aux Cerises": ("en", "Clafoutis"), "Crème Brûlée": ("en", "Crème brûlée"),
    "Panna Cotta aux Fruits Rouges": ("en", "Panna cotta"),
    "Cookies Pépites de Chocolat": ("en", "Chocolate chip cookie"),
}

FICHES_PLUS = {
    "Houmous Maison": {
        "ingredients": [
            (400, "g", "pois chiches cuits", 0.95, 0.80),
            (2, "c. à soupe", "crème de sésame (tahini)", 0.90, 0.85),
            (1, "", "citron", 0.60, 0.50),
            (1, "gousse", "ail", 0.15, 0.15),
            (3, "c. à soupe", "huile d'olive", 0.50, 0.45)],
        "etapes": ["Égouttez les pois chiches en gardant 4 cuillères à soupe de leur jus.",
                   "Mixez-les avec le tahini, le jus du citron et l'ail pelé.",
                   "Ajoutez le jus de cuisson petit à petit jusqu'à une texture onctueuse.",
                   "Salez, versez un filet d'huile d'olive et servez avec du pain pita."],
        "astuce": "Retirez la fine peau des pois chiches : le houmous sera bien plus lisse.",
        "halal": "Recette 100 % végétale, sans aucun point de vigilance particulier."},
    "Taboulé Libanais": {
        "ingredients": [
            (100, "g", "boulgour fin", 0.40, 0.35),
            (2, "bouquet", "persil plat", 1.60, 1.40),
            (3, "", "tomates mûres", 1.20, 1.40),
            (1, "bouquet", "menthe", 0.90, 0.85),
            (1, "", "citron", 0.60, 0.50),
            (3, "c. à soupe", "huile d'olive", 0.50, 0.45)],
        "etapes": ["Faites gonfler le boulgour 15 minutes dans un peu d'eau froide, puis égouttez-le.",
                   "Ciselez très finement le persil et la menthe.",
                   "Coupez les tomates en petits dés et égouttez-les.",
                   "Mélangez le tout avec le jus de citron et l'huile d'olive, salez et servez frais."],
        "astuce": "Le vrai taboulé libanais contient beaucoup plus de persil que de boulgour.",
        "halal": "Recette 100 % végétale, sans aucun point de vigilance particulier."},
    "Salade Grecque": {
        "ingredients": [
            (1, "", "concombre", 0.80, 0.70),
            (3, "", "tomates mûres", 1.20, 1.40),
            (100, "g", "feta à présure végétale", 1.80, 1.60),
            (1, "poignée", "olives noires", 0.70, 0.65),
            (1, "", "oignon rouge", 0.30, 0.25),
            (2, "c. à soupe", "huile d'olive", 0.35, 0.30)],
        "etapes": ["Coupez le concombre et les tomates en gros morceaux.",
                   "Émincez finement l'oignon rouge.",
                   "Disposez les légumes et les olives dans un saladier.",
                   "Posez la feta en bloc ou en cubes, arrosez d'huile d'olive et poivrez."],
        "astuce": "Une pincée d'origan séché sur la feta fait toute la différence.",
        "halal": "Feta à présure végétale (ou certifiée halal) ; vérifiez les olives sans alcool."},
    "Soupe de Lentilles Corail": {
        "ingredients": [
            (150, "g", "lentilles corail", 0.60, 0.50),
            (1, "", "carotte", 0.20, 0.18),
            (1, "", "oignon", 0.25, 0.20),
            (750, "ml", "bouillon de légumes", 0.50, 0.45),
            (1, "c. à café", "cumin moulu", 0.15, 0.14),
            (1, "", "citron", 0.60, 0.50)],
        "etapes": ["Épluchez et coupez la carotte et l'oignon en petits morceaux.",
                   "Faites-les revenir 3 minutes avec le cumin dans une casserole.",
                   "Ajoutez les lentilles rincées et le bouillon chaud, puis cuisez 20 minutes.",
                   "Mixez, ajoutez un trait de jus de citron et servez chaud."],
        "astuce": "Les lentilles corail ne se trempent pas : elles cuisent très vite.",
        "halal": "Vérifiez que le bouillon est 100 % végétal (sans arôme d'origine porcine)."},
    "Falafels": {
        "ingredients": [
            (400, "g", "pois chiches cuits", 0.95, 0.80),
            (1, "", "oignon", 0.25, 0.20),
            (1, "bouquet", "persil plat", 0.90, 0.80),
            (2, "c. à café", "cumin moulu", 0.30, 0.28),
            (2, "c. à soupe", "farine", 0.05, 0.05),
            (10, "cl", "huile", 0.40, 0.35)],
        "etapes": ["Égouttez bien les pois chiches et séchez-les avec du papier absorbant.",
                   "Mixez-les grossièrement avec l'oignon, le persil, le cumin, du sel et la farine.",
                   "Formez de petites boulettes aplaties avec les mains humides.",
                   "Faites-les dorer 3 à 4 minutes par face dans l'huile chaude.",
                   "Égouttez sur du papier absorbant et servez avec une sauce yaourt."],
        "astuce": "Laissez la pâte 30 minutes au frais pour que les falafels tiennent à la cuisson.",
        "halal": "Recette 100 % végétale ; utilisez une huile neuve, sans résidu de friture."},
    "Brick à l'Œuf": {
        "ingredients": [
            (2, "", "feuilles de brick", 1.20, 1.10),
            (2, "", "œufs", 0.60, 0.65),
            (1, "boîte", "thon au naturel (160 g)", 2.10, 1.90),
            (1, "bouquet", "persil plat", 0.90, 0.80),
            (10, "cl", "huile", 0.40, 0.35)],
        "etapes": ["Égouttez et émiettez le thon, mélangez-le avec le persil ciselé.",
                   "Posez une feuille de brick à plat, déposez la moitié du thon au centre et faites un creux.",
                   "Cassez un œuf dans le creux, salez, poivrez et repliez la feuille en triangle.",
                   "Faites frire 1 à 2 minutes par face dans l'huile chaude.",
                   "Égouttez et servez aussitôt avec un quartier de citron."],
        "astuce": "Humidifiez le bord de la feuille avec un doigt d'eau pour bien la fermer.",
        "halal": "Vérifiez que les feuilles de brick ne contiennent pas de graisse animale douteuse."},
    "Poulet Rôti aux Herbes": {
        "ingredients": [
            (4, "", "cuisses de poulet halal", 5.20, 4.80),
            (600, "g", "pommes de terre", 1.60, 1.40),
            (3, "gousse", "ail", 0.45, 0.45),
            (1, "c. à soupe", "thym", 0.20, 0.18),
            (1, "", "citron", 0.60, 0.50),
            (2, "c. à soupe", "huile d'olive", 0.35, 0.30)],
        "etapes": ["Préchauffez le four à 200 °C.",
                   "Coupez les pommes de terre en quartiers et disposez-les dans un plat avec l'ail écrasé.",
                   "Posez les cuisses de poulet par-dessus, ajoutez le thym, le jus du citron et l'huile.",
                   "Salez, poivrez et enfournez 50 minutes en arrosant à mi-cuisson.",
                   "Servez bien doré, avec le jus de cuisson."],
        "astuce": "Glissez un peu de thym sous la peau du poulet pour plus de parfum.",
        "halal": "Poulet certifié halal (abattage rituel) : rayon halal ou boucherie halal."},
    "Tajine de Poulet aux Olives": {
        "ingredients": [
            (4, "", "cuisses de poulet halal", 5.20, 4.80),
            (2, "", "oignon", 0.50, 0.40),
            (100, "g", "olives vertes", 0.90, 0.85),
            (1, "", "citron confit", 0.80, 0.75),
            (1, "c. à café", "ras el hanout", 0.30, 0.28),
            (1, "c. à café", "curcuma", 0.20, 0.18),
            (2, "gousse", "ail", 0.30, 0.30)],
        "etapes": ["Émincez les oignons et écrasez l'ail.",
                   "Faites dorer le poulet 5 minutes dans une cocotte, puis réservez.",
                   "Faites revenir oignons et ail avec le ras el hanout et le curcuma.",
                   "Remettez le poulet, ajoutez un grand verre d'eau et laissez mijoter 35 minutes.",
                   "Ajoutez les olives et le citron confit coupé en lamelles pour les 10 dernières minutes."],
        "astuce": "Rincez les olives pour limiter le sel, le citron confit en apporte déjà beaucoup.",
        "halal": "Poulet certifié halal ; vérifiez que le mélange d'épices ne contient pas d'alcool."},
    "Couscous au Poulet": {
        "ingredients": [
            (250, "g", "semoule moyenne", 0.60, 0.50),
            (300, "g", "blanc de poulet halal", 6.50, 5.90),
            (2, "", "carotte", 0.40, 0.36),
            (2, "", "courgettes", 1.00, 0.90),
            (200, "g", "pois chiches cuits", 0.50, 0.45),
            (1, "c. à café", "ras el hanout", 0.30, 0.28),
            (1, "", "oignon", 0.25, 0.20)],
        "etapes": ["Coupez le poulet en morceaux et les légumes en gros tronçons.",
                   "Faites revenir l'oignon et le poulet avec le ras el hanout.",
                   "Ajoutez les carottes, couvrez d'eau et cuisez 15 minutes, puis ajoutez courgettes et pois chiches 10 minutes.",
                   "Hydratez la semoule avec un volume d'eau bouillante salée, couvrez 5 minutes puis égrenez à la fourchette.",
                   "Servez la semoule avec le poulet, les légumes et le bouillon."],
        "astuce": "Ajoutez une noix de beurre dans la semoule pour des grains bien séparés.",
        "halal": "Poulet certifié halal ; ni merguez ni charcuterie sans certification."},
    "Chili con Carne": {
        "ingredients": [
            (250, "g", "bœuf haché halal", 5.20, 5.50),
            (400, "g", "haricots rouges", 0.90, 0.80),
            (400, "g", "tomates concassées", 0.95, 0.85),
            (1, "", "oignon", 0.25, 0.20),
            (1, "", "poivron rouge", 0.80, 0.70),
            (1, "c. à café", "cumin moulu", 0.15, 0.14),
            (1, "c. à café", "paprika", 0.15, 0.14)],
        "etapes": ["Émincez l'oignon et coupez le poivron en dés.",
                   "Faites revenir l'oignon, puis la viande jusqu'à ce qu'elle soit dorée.",
                   "Ajoutez le poivron, le cumin et le paprika, puis les tomates concassées.",
                   "Laissez mijoter 20 minutes, ajoutez les haricots rouges égouttés et cuisez 10 minutes de plus."],
        "astuce": "Ajoutez un carré de chocolat noir en fin de cuisson pour arrondir la sauce.",
        "halal": "Bœuf haché certifié halal ; pas de bière ni de vin dans la sauce."},
    "Lasagnes au Bœuf": {
        "ingredients": [
            (6, "", "plaques de lasagne", 1.40, 1.20),
            (250, "g", "bœuf haché halal", 5.20, 5.50),
            (400, "g", "tomates concassées", 0.95, 0.85),
            (1, "", "oignon", 0.25, 0.20),
            (40, "cl", "lait", 0.45, 0.42),
            (30, "g", "beurre", 0.50, 0.47),
            (30, "g", "farine", 0.05, 0.05),
            (80, "g", "emmental râpé à présure végétale", 1.80, 1.60)],
        "etapes": ["Préparez la sauce : faites revenir l'oignon et la viande, ajoutez les tomates et mijotez 20 minutes.",
                   "Préparez la béchamel : fondez le beurre, ajoutez la farine puis le lait en fouettant jusqu'à épaississement.",
                   "Préchauffez le four à 180 °C.",
                   "Montez le plat : sauce, plaques, béchamel, et répétez 3 fois.",
                   "Parsemez d'emmental et enfournez 30 minutes jusqu'à ce que le dessus soit doré."],
        "astuce": "Laissez reposer 10 minutes avant de couper : les parts tiendront mieux.",
        "halal": "Bœuf certifié halal ; ni jambon ni lardons, emmental à présure végétale."},
    "Curry de Pois Chiches": {
        "ingredients": [
            (400, "g", "pois chiches cuits", 0.95, 0.80),
            (200, "ml", "lait de coco", 1.10, 0.95),
            (400, "g", "tomates concassées", 0.95, 0.85),
            (1, "", "oignon", 0.25, 0.20),
            (2, "c. à café", "curry en poudre", 0.60, 0.55),
            (150, "g", "riz basmati", 1.40, 1.20)],
        "etapes": ["Mettez le riz à cuire dans l'eau bouillante salée 10 à 12 minutes.",
                   "Faites revenir l'oignon émincé avec le curry 2 minutes.",
                   "Ajoutez les tomates, le lait de coco et les pois chiches égouttés.",
                   "Laissez mijoter 15 minutes et servez sur le riz."],
        "astuce": "Une poignée d'épinards en fin de cuisson ajoute du fer et de la couleur.",
        "halal": "Recette 100 % végétale, sans aucun point de vigilance particulier."},
    "Poulet Yassa": {
        "ingredients": [
            (300, "g", "blanc de poulet halal", 6.50, 5.90),
            (4, "", "oignon", 1.00, 0.80),
            (2, "", "citron", 1.20, 1.00),
            (1, "c. à soupe", "moutarde", 0.15, 0.12),
            (2, "c. à soupe", "huile", 0.30, 0.25),
            (150, "g", "riz basmati", 1.40, 1.20)],
        "etapes": ["Marinez le poulet 30 minutes avec le jus des citrons, la moutarde, du sel et du poivre.",
                   "Émincez finement les oignons.",
                   "Faites dorer le poulet dans l'huile, puis réservez.",
                   "Faites fondre les oignons 15 minutes à feu doux, ajoutez le poulet et la marinade, et mijotez 15 minutes.",
                   "Servez sur le riz cuit."],
        "astuce": "Plus la marinade est longue, plus le poulet sera parfumé : idéal la veille.",
        "halal": "Poulet certifié halal ; vérifiez que la moutarde est sans vin."},
    "Kefta de Bœuf": {
        "ingredients": [
            (300, "g", "bœuf haché halal", 6.20, 6.60),
            (1, "", "oignon", 0.25, 0.20),
            (1, "bouquet", "persil plat", 0.90, 0.80),
            (1, "c. à café", "cumin moulu", 0.15, 0.14),
            (1, "c. à café", "paprika", 0.15, 0.14),
            (150, "g", "semoule moyenne", 0.40, 0.35)],
        "etapes": ["Hachez très finement l'oignon et le persil.",
                   "Mélangez-les à la viande avec le cumin, le paprika, du sel et du poivre.",
                   "Façonnez des boulettes allongées autour de piques ou à la main.",
                   "Faites-les cuire 10 minutes à la poêle ou au four en les retournant.",
                   "Servez avec la semoule préparée à l'eau bouillante salée."],
        "astuce": "Pétrissez longuement la viande pour que les kefta restent bien moelleuses.",
        "halal": "Bœuf haché certifié halal ; vérifiez la composition des épices du commerce."},
    "Omelette aux Champignons": {
        "ingredients": [
            (4, "", "œufs", 2.10, 2.30),
            (200, "g", "champignons de Paris", 1.30, 1.15),
            (1, "noix", "beurre", 0.15, 0.14),
            (1, "pot", "ciboulette", 0.90, 0.85),
            (1, "", "salade (cœur de laitue)", 0.90, 0.80)],
        "etapes": ["Nettoyez et émincez les champignons.",
                   "Faites-les sauter dans une poêle jusqu'à ce que l'eau s'évapore, salez et réservez.",
                   "Battez les œufs avec du sel, du poivre et la ciboulette ciselée.",
                   "Faites fondre le beurre, versez les œufs et ajoutez les champignons.",
                   "Repliez l'omelette et servez avec la salade."],
        "astuce": "Retirez la poêle du feu quand le centre est encore un peu baveux : il finit de cuire seul.",
        "halal": "Recette sans point de vigilance particulier."},
    "Cabillaud au Four": {
        "ingredients": [
            (2, "", "pavés de cabillaud", 6.80, 6.20),
            (2, "", "courgettes", 1.00, 0.90),
            (150, "g", "tomates cerises", 1.50, 1.30),
            (1, "", "citron", 0.60, 0.50),
            (2, "c. à soupe", "huile d'olive", 0.35, 0.30)],
        "etapes": ["Préchauffez le four à 190 °C.",
                   "Coupez les courgettes en rondelles et les tomates cerises en deux.",
                   "Disposez les légumes dans un plat, huilez, salez et poivrez.",
                   "Posez les pavés dessus, ajoutez des rondelles de citron et enfournez 15 minutes."],
        "astuce": "Le poisson est cuit quand la chair s'effeuille facilement à la fourchette.",
        "halal": "Poisson : aucune contrainte particulière."},
    "Gambas à l'Ail": {
        "ingredients": [
            (300, "g", "gambas crues décortiquées", 6.50, 5.90),
            (4, "gousse", "ail", 0.60, 0.60),
            (1, "bouquet", "persil plat", 0.90, 0.80),
            (1, "", "citron", 0.60, 0.50),
            (2, "c. à soupe", "huile d'olive", 0.35, 0.30),
            (150, "g", "riz basmati", 1.40, 1.20)],
        "etapes": ["Faites cuire le riz dans l'eau bouillante salée.",
                   "Écrasez l'ail et ciselez le persil.",
                   "Faites chauffer l'huile, ajoutez l'ail 30 secondes puis les gambas.",
                   "Saisissez-les 2 à 3 minutes par face jusqu'à ce qu'elles soient roses.",
                   "Ajoutez le persil et le jus de citron, puis servez sur le riz."],
        "astuce": "Ne faites pas cuire plus de 5 minutes au total : les gambas deviendraient caoutchouteuses.",
        "halal": "Les crevettes sont admises par la plupart des écoles juridiques : référez-vous à la vôtre."},
    "Hachis Parmentier": {
        "ingredients": [
            (300, "g", "bœuf haché halal", 6.20, 6.60),
            (700, "g", "pommes de terre", 1.90, 1.70),
            (1, "", "oignon", 0.25, 0.20),
            (20, "cl", "lait", 0.30, 0.28),
            (30, "g", "beurre", 0.50, 0.47),
            (40, "g", "emmental râpé à présure végétale", 0.90, 0.80)],
        "etapes": ["Épluchez les pommes de terre et cuisez-les 20 minutes à l'eau salée.",
                   "Écrasez-les avec le lait chaud et le beurre pour obtenir une purée lisse.",
                   "Faites revenir l'oignon puis la viande, salez et poivrez.",
                   "Étalez la viande dans un plat, recouvrez de purée et parsemez d'emmental.",
                   "Enfournez 20 minutes à 200 °C jusqu'à ce que le dessus soit gratiné."],
        "astuce": "Striez la purée à la fourchette : elle dorera mieux et sera plus croustillante.",
        "halal": "Bœuf haché certifié halal ; emmental à présure végétale, sans lardons."},
    "Crêpes": {
        "ingredients": [
            (125, "g", "farine", 0.10, 0.09),
            (25, "cl", "lait", 0.30, 0.28),
            (2, "", "œufs", 1.05, 1.15),
            (1, "c. à soupe", "sucre", 0.05, 0.05),
            (20, "g", "beurre", 0.35, 0.33)],
        "etapes": ["Mélangez la farine, le sucre et les œufs.",
                   "Versez le lait peu à peu en fouettant pour éviter les grumeaux.",
                   "Ajoutez le beurre fondu et laissez reposer 30 minutes.",
                   "Faites cuire une louche de pâte dans une poêle chaude, 1 minute par face."],
        "astuce": "Le repos de la pâte rend les crêpes plus souples et fines.",
        "halal": "Pas de rhum ni de Grand Marnier dans la pâte."},
    "Riz au Lait": {
        "ingredients": [
            (100, "g", "riz rond", 0.40, 0.35),
            (50, "cl", "lait", 0.60, 0.55),
            (40, "g", "sucre", 0.06, 0.05),
            (1, "c. à café", "extrait de vanille", 0.50, 0.45)],
        "etapes": ["Portez le lait à frémissement avec la vanille.",
                   "Ajoutez le riz et cuisez 30 minutes à feu très doux en remuant souvent.",
                   "Ajoutez le sucre en fin de cuisson.",
                   "Servez tiède ou froid."],
        "astuce": "Ajoutez un peu de lait si la préparation épaissit trop en refroidissant.",
        "halal": "Vérifiez que l'extrait de vanille est sans alcool (ou utilisez une gousse)."},
    "Clafoutis aux Cerises": {
        "ingredients": [
            (400, "g", "cerises", 3.00, 2.60),
            (3, "", "œufs", 1.60, 1.70),
            (20, "cl", "lait", 0.25, 0.23),
            (60, "g", "farine", 0.07, 0.07),
            (60, "g", "sucre", 0.09, 0.08)],
        "etapes": ["Préchauffez le four à 180 °C et beurrez un plat.",
                   "Fouettez les œufs avec le sucre, ajoutez la farine puis le lait.",
                   "Disposez les cerises lavées et équeutées dans le plat.",
                   "Versez la pâte dessus et enfournez 35 minutes."],
        "astuce": "Gardez les noyaux : ils donnent un léger goût d'amande à la cuisson.",
        "halal": "Pas de kirsch : le clafoutis traditionnel n'en a pas besoin."},
    "Crème Brûlée": {
        "ingredients": [
            (25, "cl", "crème liquide", 1.40, 1.30),
            (3, "", "jaunes d'œufs", 0.90, 0.95),
            (40, "g", "sucre", 0.06, 0.05),
            (1, "c. à café", "extrait de vanille", 0.50, 0.45),
            (2, "c. à soupe", "cassonade", 0.10, 0.09)],
        "etapes": ["Préchauffez le four à 100 °C.",
                   "Fouettez les jaunes avec le sucre, ajoutez la crème et la vanille.",
                   "Versez dans deux ramequins et enfournez 40 minutes, puis laissez refroidir.",
                   "Au moment de servir, saupoudrez de cassonade et caramélisez au chalumeau ou sous le gril."],
        "astuce": "Réfrigérez au moins 2 heures avant de caraméliser pour un contraste chaud/froid.",
        "halal": "Vanille sans alcool ; pas de liqueur ni de Grand Marnier."},
    "Panna Cotta aux Fruits Rouges": {
        "ingredients": [
            (25, "cl", "crème liquide", 1.40, 1.30),
            (15, "cl", "lait", 0.20, 0.19),
            (40, "g", "sucre", 0.06, 0.05),
            (1, "c. à café", "agar-agar", 0.60, 0.55),
            (150, "g", "fruits rouges", 2.20, 1.90)],
        "etapes": ["Mélangez crème, lait, sucre et agar-agar dans une casserole.",
                   "Portez à ébullition 1 minute en remuant.",
                   "Versez dans des verrines et laissez refroidir, puis réfrigérez 3 heures.",
                   "Servez nappé de fruits rouges."],
        "astuce": "Écrasez la moitié des fruits avec un peu de sucre pour faire un coulis.",
        "halal": "L'agar-agar remplace la gélatine, souvent d'origine porcine : à privilégier."},
    "Cookies Pépites de Chocolat": {
        "ingredients": [
            (150, "g", "farine", 0.10, 0.09),
            (80, "g", "beurre", 1.50, 1.40),
            (80, "g", "sucre", 0.12, 0.10),
            (1, "", "œufs", 0.50, 0.55),
            (100, "g", "pépites de chocolat", 1.40, 1.20)],
        "etapes": ["Préchauffez le four à 180 °C.",
                   "Travaillez le beurre mou avec le sucre, puis ajoutez l'œuf.",
                   "Incorporez la farine puis les pépites de chocolat.",
                   "Déposez des boules de pâte espacées sur une plaque et enfournez 10 à 12 minutes."],
        "astuce": "Sortez les cookies quand les bords sont dorés : le centre durcira en refroidissant.",
        "halal": "Pépites de chocolat sans alcool ni liqueur."},
}
